# Generated by Django 4.2 on 2025-10-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='class15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('pnumb', models.CharField(max_length=500)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('id_card', models.FileField(upload_to='')),
            ],
        ),
    ]
