# Generated by Django 4.2 on 2025-09-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('course', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=10)),
            ],
        ),
    ]
