# Generated by Django 4.2 on 2025-09-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home13',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='home13',
            name='title',
            field=models.CharField(default='Untitled', max_length=50),
        ),
    ]
