# Generated by Django 4.2 on 2025-10-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=500)),
                ('years_of_experience', models.CharField(max_length=200)),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
    ]
